# Generated by Django 2.2.12 on 2020-06-12 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('numero_conta', models.IntegerField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('cod_user', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_agencia', models.IntegerField()),
            ],
        ),
    ]
