# Generated by Django 2.2.12 on 2020-06-12 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usuario_numero_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('cod_agencia', models.IntegerField()),
                ('numero_conta', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
