# Generated by Django 2.2.12 on 2020-06-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_clientes_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
